\hypertarget{classDynamicVectorException}{}\doxysubsection{Dynamic\+Vector\+Exception Class Reference}
\label{classDynamicVectorException}\index{DynamicVectorException@{DynamicVectorException}}


{\ttfamily \#include $<$Exceptions.\+h$>$}



Inheritance diagram for Dynamic\+Vector\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=220pt]{classDynamicVectorException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for Dynamic\+Vector\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=220pt]{classDynamicVectorException__coll__graph}
\end{center}
\end{figure}
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classDynamicVectorException_a112b831417be0bd0dec4eaedfcfb1b17}\label{classDynamicVectorException_a112b831417be0bd0dec4eaedfcfb1b17}} 
{\bfseries Dynamic\+Vector\+Exception} (const std\+::string \&message)
\end{DoxyCompactItemize}


\doxysubsubsection{Detailed Description}
Dynamic\+Vector exception 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
include/domain/\mbox{\hyperlink{Exceptions_8h}{Exceptions.\+h}}\end{DoxyCompactItemize}
